name: CI

on:
  push:
    branches: [main]
    paths:
      - grammar.js
      - src/**
      - test/**
      - queries/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # skip: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.6
      - name: Set up examples
        run: |-
          git clone https://github.com/ffcabbar/MIPS-Assembly-Language-Examples --single-branch --depth=1 --filter=blob:none
          git clone https://github.com/ClaudioKamoda/MIPS-Assembly-Projects --single-branch --depth=1 --filter=blob:none
          git clone https://github.com/AleksandrHovhannisyan/MIPS-Linked-List --single-branch --depth=1 --filter=blob:none
          git clone https://github.com/apebl/mips-asm-examples --single-branch --depth=1 --filter=blob:none
          git clone https://github.com/erenulas/mips-assembly-examples --single-branch --depth=1 --filter=blob:none
          git clone https://github.com/rohitdwivedula/mips-exercises --single-branch --depth=1 --filter=blob:none
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: false
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |
            **/*.s
            **/*.asm
          invalid-files: |
            MIPS-Assembly-Language-Examples/mips-6-ifElseAdder.asm
            MIPS-Assembly-Projects/GuessingGame.asm
            MIPS-Assembly-Projects/RoboQueSegueLinha.asm
            mips-asm-examples/macros.asm
